apriltag:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.05
    profile: false
    max_hamming: 0
    pose_estimation_method: pnp
    detector:
      threads: 1
      decimate: 2.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false
