<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>industrial_vision_bringup</name>
  <version>0.1.0</version>
  <description>Unified Basler, AprilTag and QR vision pipeline bringup.</description>
  <maintainer email="jason889977@users.noreply.github.com">jason889977</maintainer>
  <license>BSD-3-Clause</license>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>apriltag_ros</exec_depend>
  <exec_depend>apriltag_pose_reader</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>pylon_ros2_camera_wrapper</exec_depend>
  <exec_depend>qrcode_detector</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
