# Throughput/stability tuned v3 profile for basler acA2500-14GC (S/N: 22297684)
# v3 strategy: keep network-safe GigE settings and reduce payload via binning.
/**:
  ros__parameters:
    camera_frame: basler_aca2500_106611_18
    device_user_id: "apriltagCam"
    serial_number: "22297684"
    user_id: "apriltagCam"
    mac: "00:30:53:23:0f:54"
    ip: "172.31.0.88"
    model: "acA2500-14gc"
    camera_info_url: "package://pylon_ros2_camera_wrapper/config/aca2500_106611_18.calib.yaml"
    frame_rate: 8.0
    grab_timeout: 1500
    mtu_size: 1500
    inter_pkg_delay: 1000
    binning_x: 2
    binning_y: 2
