# High-throughput camera profile for basler acA2500-14GC (S/N: 22297681)
/**:
  ros__parameters:
    camera_frame: basler_aca2500_106611_18
    device_user_id: "106611-18"
    serial_number: "22297681"
    user_id: "106611-18"
    mac: ""
    ip: "172.31.0.88"
    model: "acA2500-14gc"
    camera_info_url: "package://pylon_ros2_camera_wrapper/config/aca2500_106611_18.calib.yaml"
    image_encoding: mono8
    frame_rate: -1.0
    exposure: 10000.0
    grab_timeout: 1000
    grab_strategy: 1
    binning_x: 2
    binning_y: 2
    mtu_size: 1500
    inter_pkg_delay: 0
